const profileTempData = {
  firstName: "Ege",
  lastName: "Aydemir",
  email: "egeaydemirr97@gmail.com",
  petName: "Saki",
  petType: "Köpek",
  petBreed: "Setter",
  petAge: "1",
  petWeight: "10",
  petGender: "Erkek",
  petColor: "Beyaz",
  petSpayed: "Hayır",
  petVaccinated: "Evet",
  petMicrochipped: "Hayır",
  petDietaryRestrictions: "Kuru mama",
  petAllergies: "Yok",
  petMedications: "Yok",
  petBehaviorIssues: "Yok",
  petSpecialNeeds: "Yok",
  profilePicture: "/images/saki.jpg",
  petAbout: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
  petLocation: "Ankara",
};
export default profileTempData;